### PR TITLE
chore: Remove travis webhook

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit b362b27 has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit b362b27 with merge 49bf075...

**Comment by ghost** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/badboy/testh/builds/123546047)

**Pull request merged**
