### PR TITLE
chore: Enable homu

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
@not-a-robot r+

**Comment by ghost** [comment]
:pushpin: Commit 74487dc has been approved by `badboy`

**Comment by ghost** [comment]
:hourglass: Testing commit 74487dc with merge 2553b94...

**Comment by ghost** [comment]
:sunny: Test successful - [travis](https://travis-ci.org/badboy/testh/builds/123388562)

**Pull request merged**
